server:
  port: 9003

spring:
  application:
    name: bngelbook-account-consumer
  jackson:
    date-format: yyyy-MM-dd
  servlet:
    multipart:
      max-file-size: 20MB
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
      config:
        server-addr: localhost:8848
        file-extension: yaml

feign:
  httpclient:
    connection-timeout: 4000
